<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="8" failures="1" disabled="0" errors="0" timestamp="2017-06-30T00:09:32" time="0.018" name="AllTests">
  <testsuite name="Test_Graph" tests="8" failures="1" disabled="0" errors="0" time="0.013">
    <testcase name="PointToTwoVertices" status="run" time="0" classname="Test_Graph" />
    <testcase name="PointToOneVerticesAndPointedByAnotherOne" status="run" time="0" classname="Test_Graph" />
    <testcase name="HasCycleWithThreeVertices" status="run" time="0" classname="Test_Graph" />
    <testcase name="HasCycleAroundAVertex" status="run" time="0.001" classname="Test_Graph" />
    <testcase name="GraphHasCycleButV3IsNotInCycle" status="run" time="0.001" classname="Test_Graph">
      <failure message="d:\projects\hope_love\unittest\test_graph.cpp:69&#x0A;Value of: _graphWithCycle.HasCycle(_v3)&#x0A;  Actual: true&#x0A;Expected: false" type=""><![CDATA[d:\projects\hope_love\unittest\test_graph.cpp:69
Value of: _graphWithCycle.HasCycle(_v3)
  Actual: true
Expected: false]]></failure>
    </testcase>
    <testcase name="HasNoCycle" status="run" time="0" classname="Test_Graph" />
    <testcase name="GenerateSubGraphOfDisconnectedGraph" status="run" time="0.001" classname="Test_Graph" />
    <testcase name="GenerateSubGraphOfDisconnectedGraph2" status="run" time="0.001" classname="Test_Graph" />
  </testsuite>
</testsuites>
