<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="5" failures="1" disabled="0" errors="0" timestamp="2017-06-27T01:15:31" time="27.118" name="AllTests">
  <testsuite name="Test_Graph" tests="5" failures="1" disabled="0" errors="0" time="27.115">
    <testcase name="PointToTwoVertices" status="run" time="0" classname="Test_Graph" />
    <testcase name="PointToOneVerticesAndPointedByAnotherOne" status="run" time="0" classname="Test_Graph" />
    <testcase name="HasCycleWithThreeVertices" status="run" time="0" classname="Test_Graph" />
    <testcase name="HasCycleAroundAVertex" status="run" time="12.887" classname="Test_Graph">
      <failure message="d:\projects\hope_love\unittest\test_graph.cpp:83&#x0A;Value of: graph.HasCycle(v0)&#x0A;  Actual: false&#x0A;Expected: true" type=""><![CDATA[d:\projects\hope_love\unittest\test_graph.cpp:83
Value of: graph.HasCycle(v0)
  Actual: false
Expected: true]]></failure>
    </testcase>
    <testcase name="HasNoCycle" status="run" time="14.222" classname="Test_Graph" />
  </testsuite>
</testsuites>
